package examiner

import "github.com/binoctal/cerberus/internal/head/agent"

// JudgeStatus represents the verdict of a test step evaluation.
type JudgeStatus string

const (
	StatusPass      JudgeStatus = "pass"
	StatusFail      JudgeStatus = "fail"
	StatusUncertain JudgeStatus = "uncertain"
	StatusSkip      JudgeStatus = "skip"
)

// JudgeResult is the output of a Judge evaluation.
type JudgeResult struct {
	Status                JudgeStatus `json:"status"`
	ExistenceConfidence   float64     `json:"existence_confidence"`
	CorrectnessConfidence float64     `json:"correctness_confidence"`
	Reasoning             string      `json:"reasoning"`
	SelfCritique          string      `json:"self_critique,omitempty"`
	CritiqueTriggered     bool        `json:"critique_triggered,omitempty"`
}

// CritiqueResult is the output of a Self-Refine critique pass.
type CritiqueResult struct {
	IssuesFound        bool        `json:"issues_found"`
	Critique           string      `json:"critique"`
	SuggestedStatus    JudgeStatus `json:"suggested_status"`
	SuggestedConfidence float64    `json:"suggested_confidence"`
}

// Reflection represents a single reflection generated by the Learner.
type Reflection struct {
	Type             string  `json:"type"`              // "failure" or "success"
	Diagnosis        string  `json:"diagnosis"`
	Strategy         string  `json:"strategy"`
	ConditionPattern string  `json:"condition_pattern"`
	Category         string  `json:"category"`
}

// LearnInput bundles all step results for a Reflexion learning pass.
type LearnInput struct {
	SessionID  string
	Project    string
	Results    []agent.StepResult
}

// ExaminerConfig holds configuration for the Examiner head.
type ExaminerConfig struct {
	MaxCritiques  int     // Session-level max critique count (default 1)
	ConfThreshold float64 // Confidence threshold for early stop (default 0.9)
	AutoFix       string  // Auto-fix mode: "off", "low_only", "aggressive" (default "low_only")
}

func DefaultExaminerConfig() ExaminerConfig {
	return ExaminerConfig{
		MaxCritiques:  1,
		ConfThreshold: 0.9,
		AutoFix:       "low_only",
	}
}
